pos_tags = {
    'CC': 'Conjunção coordenativa (and, but, or)',
    'CD': 'Número cardinal (one, two, 100)',
    'DT': 'Determinante (the, a, an)',
    'EX': 'There existencial (there is)',
    'FW': 'Palavra estrangeira (c’est la vie)',
    'IN': 'Preposição ou conjunção subordinativa (in, of, although)',
    'JJ': 'Adjetivo (big, nice)',
    'JJR': 'Adjetivo comparativo (bigger, nicer)',
    'JJS': 'Adjetivo superlativo (biggest, nicest)',
    'LS': 'Marcador de item de lista (1), a))',
    'MD': 'Verbo modal (can, should, will)',
    'NN': 'Substantivo singular ou incontável (dog, music)',
    'NNS': 'Substantivo plural (dogs, cars)',
    'NNP': 'Nome próprio singular (John, London)',
    'NNPS': 'Nome próprio plural (Americans, Beatles)',
    'PDT': 'Predeterminante (all, both)',
    'POS': 'Apóstrofo de posse (\'s)',
    'PRP': 'Pronome pessoal (I, you, he)',
    'PRP$': 'Pronome possessivo (my, your)',
    'RB': 'Advérbio (quickly, never)',
    'RBR': 'Advérbio comparativo (better, faster)',
    'RBS': 'Advérbio superlativo (best, fastest)',
    'RP': 'Partícula (up, off)',
    'SYM': 'Símbolo (%, $, +)',
    'TO': 'Partícula "to" (to go)',
    'UH': 'Interjeição (oh, wow)',
    'VB': 'Verbo base (go, eat)',
    'VBD': 'Verbo no passado (went, ate)',
    'VBG': 'Gerúndio / presente contínuo (going, eating)',
    'VBN': 'Particípio passado (gone, eaten)',
    'VBP': 'Presente (não 3ª pessoa) (go, eat)',
    'VBZ': 'Presente 3ª pessoa (goes, eats)',
    'WDT': 'Determ. relativo (which, that)',
    'WP': 'Pronome relativo (who, what)',
    'WP$': 'Pronome relativo possessivo (whose)',
    'WRB': 'Advérbio relativo (where, when)',
    '.': 'Pontuação final (. ? !)',
    ',': 'Vírgula (,)',
    ':': 'Dois-pontos / travessão (: —)',
    '``': 'Aspas de abertura',
    '\'\'': 'Aspas de fechamento',
    '$': 'Símbolo de dólar ($)',
    '#': 'Sinal de número (#)',
}
